version = 1

[[analyzers]]
name = "python"

  [analyzers.meta]
  runtime_version = "3.x.x"

[[analyzers]]
name = "cxx"

[[transformers]]
name = "autopep8"

[[transformers]]
name = "clang-format"

[[analyzers]]
name = "test-coverage"
enabled = true
